### ISSUE TITLE
EPIC: The API exposes both CUDA and CPU based coupled decomposition algorithms.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#179]
DoD:

- [x] Initial CPU implementation
- [x] CPU testing and test case
- [ ] Initial CUDA implementation
- [ ] CUDA testing(?)  - this is going to need to be a conditional test I fear.

**Comment by jlaura** [comment]
The CPU implementation has been debugged and is functioning as intended.  The CUDA implementation is not and should not be used due to intermittent memory errors.  I am doing something wrong in how the GPU memory is being managed.
